GET http://localhost:3001/fetch HTTP/1.1


###
GET http://localhost:3002/get?id=1 HTTP/1.1


###
GET http://localhost:3002/flush HTTP/1.1


###
GET http://localhost:3000/news/predict HTTP/1.1


###
GET http://localhost:3000/news/train HTTP/1.1


###