GET http://localhost:3001/fetch HTTP/1.1


###
GET http://localhost:3002/docx HTTP/1.1


###
GET http://localhost:3002/get/other/1 HTTP/1.1


###
POST http://localhost:3002/update/qualcomm/1 HTTP/1.1
content-type: application/json

{ "title": "通驍龍meow" }


###
GET http://localhost:3000/news/train HTTP/1.1


###